# Generated by Django 3.2 on 2023-07-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lisensedata',
            name='height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
